export const strokes = [
{ mandarin: '横', pinyin: 'héng', type: 'Horizontal', examples: '一，二，三，王，工', img: require('/assets/writing/strokes/images/1.png') },
{ mandarin: '提', pinyin: 'tí', type: 'Rising Stroke', examples: '习，地，冷，冰，刁', img: require('/assets/writing/strokes/images/2.png') },
{ mandarin: '长竖', pinyin: 'cháng, shù', type: 'Long vertical', examples: '书，快，师，十，市', img: require('/assets/writing/strokes/images/3.png') },
{ mandarin: '短竖', pinyin: 'duǎn, shù', type: 'Short vertical', examples: '刊，修，候，刚，利', img: require('/assets/writing/strokes/images/4.png') },
{ mandarin: '竖钩', pinyin: 'shù, gōu', type: 'Vertical hook', examples: '小，水，求，寸，找', img: require('/assets/writing/strokes/images/5.png') },
{ mandarin: '撇', pinyin: 'piě', type: 'Left falling', examples: '月，木，大，人，个', img: require('/assets/writing/strokes/images/6.png') },
{ mandarin: '横撇', pinyin: 'héng, piě', type: 'Shorter and horizontal left falling', examples: '千，舌，毛，白，禾', img: require('/assets/writing/strokes/images/7.png') },
{ mandarin: '短点', pinyin: 'duǎn, diǎn', type: 'Short dot', examples: '主，广，心，注，文', img: require('/assets/writing/strokes/images/8.png') },
{ mandarin: '长点', pinyin: 'cháng, diǎn', type: 'Long dot', examples: '双，不，贝，头', img: require('/assets/writing/strokes/images/9.png') },
{ mandarin: '左点', pinyin: 'zuǒ, diǎn', type: 'Left dot', examples: '办，刃，心，必，小', img: require('/assets/writing/strokes/images/10.png') },
{ mandarin: '平捺', pinyin: 'píng, nà', type: 'horizontal right falling', examples: '之，延，这，走', img: require('/assets/writing/strokes/images/11.png') },
{ mandarin: '斜捺', pinyin: 'xié, nà', type: 'slanted right falling', examples: '又，义，个，人，大', img: require('/assets/writing/strokes/images/12.png') },
{ mandarin: '横折', pinyin: 'héng, zhé', type: 'Horizontal turning', examples: '口，问', img: require('/assets/writing/strokes/images/13.png') },
{ mandarin: '横折提', pinyin: 'héng, zhé, tí', type: 'Horizontal turning and rising', examples: '说，话，讨，论，讲', img: require('/assets/writing/strokes/images/14.png') },
{ mandarin: '横撇', pinyin: 'héng, piě', type: 'Horizontal and left-falling', examples: '又，反', img: require('/assets/writing/strokes/images/15.png') },
{ mandarin: '横折钩', pinyin: 'héng, zhé, gōu', type: 'Horizontal turning and hook', examples: '刀，门，也', img: require('/assets/writing/strokes/images/16.png') },
{ mandarin: '横钩', pinyin: 'héng, gōu', type: 'Horizontal hook', examples: '买，皮，卖', img: require('/assets/writing/strokes/images/17.png') },
{ mandarin: '横折斜钩', pinyin: 'héng, zhé, xié, gōu', type: 'Horizontal and slanted hook', examples: '飞，风，凤，凰', img: require('/assets/writing/strokes/images/18.png') },
{ mandarin: '横折弯钩', pinyin: 'héng, zhé, wān, gōu', type: 'Horizontal turning and curved hook', examples: '几，九，匹', img: require('/assets/writing/strokes/images/19.png') },
{ mandarin: '横折弯', pinyin: 'héng, zhé, wān', type: 'Horizontal turning and curved turning', examples: '朵，铅', img: require('/assets/writing/strokes/images/20.png') },
{ mandarin: '横折折', pinyin: 'héng, zhé, zhé', type: 'Horizontal turning and turning', examples: '凹', img: require('/assets/writing/strokes/images/21.png') },
{ mandarin: '横折折撇', pinyin: 'héng, zhé, zhé, piě', type: 'Horizontal turning and turning left-falling', examples: '廷，建', img: require('/assets/writing/strokes/images/22.png') },
{ mandarin: '横折折折', pinyin: 'héng, zhé, zhé, zhé', type: '', examples: '凸', img: require('/assets/writing/strokes/images/23.png') },
{ mandarin: '横折撇弯钩', pinyin: 'héng, zhé, piě, wān, gōu', type: '', examples: '阵，队，除', img: require('/assets/writing/strokes/images/24.png') },
{ mandarin: '横折折折钩', pinyin: 'héng, zhé, zhé, zhé, gōu', type: '', examples: '乃，奶', img: require('/assets/writing/strokes/images/25.png') },
{ mandarin: '竖折', pinyin: 'shù, zhé', type: 'Vertical turning', examples: '山，匹', img: require('/assets/writing/strokes/images/26.png') },
{ mandarin: '竖弯', pinyin: 'shù, wān', type: 'Vertical curved turning', examples: '四', img: require('/assets/writing/strokes/images/27.png') },
{ mandarin: '竖提', pinyin: 'shù, tí', type: 'Vertical and rising', examples: '民，切', img: require('/assets/writing/strokes/images/28.png') },
{ mandarin: '竖折折', pinyin: 'shù, zhé, zhé', type: 'Vertical turning and vertical', examples: '鼎', img: require('/assets/writing/strokes/images/29.png') },
{ mandarin: '竖折折撇', pinyin: 'shù, zhé, zhé, piě', type: 'Vertical turning and left-falling', examples: '专，传', img: require('/assets/writing/strokes/images/30.png') },
{ mandarin: '竖弯钩', pinyin: 'shù, wān, gōu', type: 'Vertical curved hook', examples: '儿，乱', img: require('/assets/writing/strokes/images/31.png') },
{ mandarin: '竖折折钩', pinyin: 'shù, zhé, zhé, gōu', type: 'Vertical turning and turning hook', examples: '与，马', img: require('/assets/writing/strokes/images/32.png') },
{ mandarin: '撇折', pinyin: 'piě, zhé', type: 'Left falling and turning', examples: '么，公', img: require('/assets/writing/strokes/images/33.png') },
{ mandarin: '撇点', pinyin: 'piě, diǎn', type: 'Left-falling and dot', examples: '女，巡', img: require('/assets/writing/strokes/images/34.png') },
{ mandarin: '弯钩', pinyin: 'wān, gōu', type: 'Curved hook', examples: '家，了，子', img: require('/assets/writing/strokes/images/35.png') },
{ mandarin: '斜钩', pinyin: 'xié, gōu', type: 'Slanted hook', examples: '戈，我，伐', img: require('/assets/writing/strokes/images/36.png') },
];


export const order = [
{ name: 'Top to bottom', mandarin: '从上到下 (cóng shàng dào xià)', img: require('/assets/writing/strokes/images/order1.gif') },
{ name: 'Left to right', mandarin: '从左到右 (cóng zuǒ dào yòu)', img: require('/assets/writing/strokes/images/order2.gif') },
{ name: 'First horizontal, then vertical', mandarin: '先横后竖 (xiān héng hòu shù)', img: require('/assets/writing/strokes/images/order3.gif') },
{ name: 'First right-to-left diagonals, then left-to-right diagonals', mandarin: '先撇后捺 (xiān piē hòu nà)', img: require('/assets/writing/strokes/images/order4.gif') },
{ name: 'Center comes first in vertically symmetrical characters', mandarin: '先中间后两边 (xiān zhōngjiān hòu liǎngbiān)', img: require('/assets/writing/strokes/images/order5.gif') },
{ name: 'Move from outside to inside and close frames last', mandarin: '从外到内 (cóng wài dào nèi)\n先进后关 (xiān jìn hòu guān)', img: require('/assets/writing/strokes/images/order6.gif') }
];
